#!/usr/bin/env bash

if [[ $(whoami) != root ]]; then
    echo "must be run as root" 1>&2
    exit 1
fi

pere_dir=/usr/lib/pere
pere_src_dir="$(dirname "$(realpath "$0")")"
bin_dir=/usr/bin

if [[ ! -d ${pere_dir} ]]; then
    mkdir "${pere_dir}"
fi

cp "${pere_src_dir}/pere" "${bin_dir}"
cp "${pere_src_dir}/pere.lua" "${pere_dir}"
